on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: bytestream.azurecr.io
        username: ${{ secrets.acr_bytestream_username }}
        password: ${{ secrets.acr_bytestream_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t bytestream.azurecr.io/akscluster01:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push bytestream.azurecr.io/akscluster01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akscluster01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep todoapi-ns | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace todoapi-ns`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: todoapi-ns
        container-registry-url: bytestream.azurecr.io
        container-registry-username: ${{ secrets.acr_bytestream_username }}
        container-registry-password: ${{ secrets.acr_bytestream_password }}
        secret-name: akscluster01dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: todoapi-ns
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          bytestream.azurecr.io/akscluster01:${{ github.sha }}
        imagepullsecrets: |
          akscluster01dockerauth
